#!/bin/bash

# Basic dependencies
brew install zsh coreutils vim nvm php@7.3 tmux composer ack wget mas gist jq

# Cask dependencies
brew cask install typinator spotify alfred bartender diffmerge postman 1password 1password-cli microsoft-teams

# Add brew zsh to the shells file
if grep -q "/usr/local/bin/zsh" /etc/shells; then
	echo "zsh already in /etc/shells"
else
	echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
fi

# Update shell to homebrew zsh
chsh -s /usr/local/bin/zsh
