#!/usr/bin/env bash
# Create a wpframe session

mkdir $1
cd $1

git init

touch wpframe

git add wpframe

git commit -m 'Initial commit'

git remote add wpframe git@github.com:vanpattenmedia/wpframe.git

git fetch wpframe

git merge --squash wpframe/master

rm wpframe

mv config/database.example.yml config/database.yml

echo '<?php' > wp-salts.php && curl https://api.wordpress.org/secret-key/1.1/salt >> config/wp-salts.php
